apiVersion: v1
kind: Service
metadata:
  name: nextargo-service
spec:
  selector:
    app: nextargo-pod
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30003
      protocol: TCP